### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by EDDYMENS**
Finally done with my project and had time to properly go over the docs 

Not done yet but here is what I have so far

## Minor

- Grammar fix and rewording

## Major
- Updated broken URL references, eg: https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions => https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.launchoptions.md
- Fix for calling of `getDevice` on a `browserContext` instead of a browser instance [Here](https://github.com/microlinkhq/browserless/pull/577/commits/452293ea226e51a605e4e135cba91506dec698a5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R148-R160)

## I am not sure (Just a suggestion)

- Dropped the use of `$` in the bash snippets (Copying to clipboard copies the symbol) [Line 27](https://github.com/microlinkhq/browserless/pull/577/commits/452293ea226e51a605e4e135cba91506dec698a5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R27)

### CODE REVIEW

**Comment by Kikobeats** [comment]
oh wow, thanks for this, really appreciated.

Can you feedback me about browserless? Did you find it useful for your project? What can be improved (besides doc 😬) ?

**Comment by EDDYMENS** [comment]
@Kikobeats sure personally I really like the idea of the CLI tool. 
I am a technical writer and from time to time I need to do things like check if the links on the page are broken etc. 

The idea of a CLI is very very helpful in this case since I don't have to do everything in code but instead, I get to use a more declarative approach with commands. This is the project I was working on.

If the CLI had browser actions baked in eg: > goto example.com & click [div#menu] &  screenshot ` that would be another level but I don't think that's the goal of this project.

I also love the screenshot feature with the browser stencil, I am not much of a graphic designer, but for me to be able to easily place my screenshot in a browser stencil using code, I am all for it.

**Comment by Kikobeats** [comment]
Thanks for the feedback!

I have another project for detecting broken links and it uses browserless by default, check 
https://github.com/urlint/urlint 🙂

BTW I think this is kind of what you describe https://github.com/urlint/urlint/issues/57

**Comment by EDDYMENS** [comment]
> Thanks for the feedback!
> 
> I have another project for detecting broken links and it uses browserless by default, check https://github.com/urlint/urlint 🙂
> 
> BTW I think this is kind of what you describe [urlint/urlint#57](https://github.com/urlint/urlint/issues/57)

This is nice! so I just checked it out and set prerender to `true` because the site I tested it on is an SPA, but it seems to miss the broken link on the site.

**Pull request merged**
